export const enum PermissionEnum {
  VIEW_DASHBOARD = "VIEW_DASHBOARD",
  VIEW_ROLE_PERMISSION = "VIEW_ROLE_PERMISSION",
  MANAGE_ROLE_PERMISSION = "MANAGE_ROLE_PERMISSION",
  VIEW_USER = "VIEW_USER",
  EDIT_USER_INFO = "EDIT_USER_INFO",
  CAN_DELETE = "CAN_DELETE",
}
